# number of points in one cubic bezier
number_of_points: 100
bloating : 0

vehicle_width : 1.75

vehicle_length : 2.65

  # the range for local mutation, unit is [meter]
local_search_range_radius : 0.5
# /**
#  * @brief the range for local mutation, unit is [rad],for angle, this value must small than 2*pi
#  * 
#  */
local_search_range_angle: 0.5
# position_resolution : 1

# headings : 72

manual : true

# dubins_lookup : false

cell_size : 1
  
#  population size of chromosome 
population_size : 10
#  penalty for fitness function
penalty_fitness : 70

  # use to switch mutation mode 
h_s : 10
  #  use to terminate revolution process
h_t : 20

